### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by helinal** [toppahattu/tsoha-golf_courses#1]
### Käyttökokemus
- Yleinen käyttökokemus on hyvä, sovellusta on helppo käyttää ja ulkoasu sekä rakenne ovat selkeitä
- Sovellus on hyvin edistynyt ja hyvällä mallilla
- Muutamia pieniä parannusehdotuksia:
  - Peruskäyttäjälle etusivulla näkyvän kenttälistan sijainti oikeassa reunassa on hieman hankala, etenkin jos sovellusta käyttää koko näytöllä
  - Etusivulla ja golfkenttien sivuilla on käytössä eri fontti - ulkonäön puolesta olisi kenties siistimpää käyttää samaa fonttia koko sovelluksessa
  - Myös ylläpitäjille voisi näkyä kaikkien golfkenttien lista etusivulla

### Koodi ja tietokanta
- Koodi on siistiä ja helposti luettavaa
- Tietokanta näyttää loogiselta; tietokantataulujen nimet ovat kuvaavia ja rakenne hyvä
- Tietoturva on kunnossa ainakin kurssimateriaalissa mainittujen haavoittuvuuksien osalta

Kaiken kaikkiaan hyvää työtä! :)

**Comment by toppahattu** [comment]
#1
Kenttälista siirretty etusivulla vasempaan reunaan. 3fc17cad6ac6c5169ce4ce6c56327e9bda23dfb6

**Comment by toppahattu** [comment]
#1
Näytetään etusivun kenttälista myös ylläpitäjälle. a6fc5ad4fe0b776464628c832f479ed3433aa450

**Comment by toppahattu** [comment]
#1
Ulkoasua yhtenäistetty mm. fontin osalta. 44fe3ede2aaf0eeb74738dd863a5b541d792877a

**Comment by toppahattu** [comment]
Kiitos kommenteista ja ehdotuksista! Yläpuolelle linkatuissa commiteissa on toteutettu ehdottamiasi muutoksia.
